const BANNERS = {
  "现实破译法": { name: "Deciphering Reality", type: "Character", rateUp6: ["Enigma"] },
  "虹色五线谱": { name: "Playing in Rainbow Clef", type: "Character", rateUp6: ["Barcarola"] },
  "晴日决胜局": { name: "Clash 'n' Slash", type: "Character", rateUp6: ["J"] },
  "零重力漫游": { name: "Wirewalking in Zero Gravity", type: "Character", rateUp6: ["Kiperina"]},
  "渡影归真": { name: "Conduit of the Unseen", type: "Character", rateUp6: ["Ramona"] },
  "奇异吸引子": { name: "The Strange Attractor", type: "Character", rateUp6: ["Lorentz Butterfly"] },
  "虚影的实鉴": { name: "Observation into the Mirrors", type: "Character", rateUp6: ["Kakania"] },
  "鸿羽若有凌云志" : { name: "Soaring Aspirations", type: "Character", rateUp6: ["Cheng Heguang"] },
  "幕间蒙太奇" : { name: "A Life in Montage", type: "Character", rateUp6: ["Noire"] },
  "赤心如昼明" : { name: "Moonbeam Guardian", type: "Limited", rateUp6: ["Liang Yue"]},
  "湖心追述" : { name: "From the Lake's Heart", type: "Water", rateUp6: ["Jiu Niangzi", "Lucy", "Anjo Nala", "Liang Yue"]},
  "子夜独角戏" : { name: "The Midnight Flutist", type: "Character", rateUp6: ["Rubuska"]},
  "剪春注我" : { name: "Her Heart-Cut Spring", type: "Limited", rateUp6: ["Paper Heron"]},
  "湖的启示" : { name: "Revelation of the Water", type: "Water" },
  "鳞与石的世纪" : { name: "Serpentine Century", type: "Character", rateUp6: ["Hissabeth"] },
  "度朔飞琼" : { name: "The Snow of Dushuo", type: "Special" },
  "湖的企盼" : { name: "Yearning of the Water", type: "Water" },
  "铁与血的亲证": { name: "Witness of Iron and Blood", type: "Character", rateUp6: ["Igor"]},
  "午夜摇篮曲" : { name: "Blue Lullaby", type: "Character", rateUp6: ["Tuesday"]},
  "修缮往日": { name: "From the Ruin of the Past", type: "Character", rateUp6: ["Moldir"]},
  "誓言无有烬时": { name: "The Oath Unyielding", type: "Character", rateUp6: ["Marsha"]},
  "思维动力学":   { name: "Cognitive Dynamics", type: "Character", rateUp6: ["Ulrich"]},
  "永恒折射角":   { name: "The Brilliance Within", type: "Character", rateUp6: ["Brume"]},
  "仙子振翅入夜": { name: "The Fairies Shining at Night", type: "Character", rateUp6: ["Tooth Fairy"]},
  "命运亦需捧场": { name: "On Fate's Cue", type: "Limited", rateUp6: ["Beryl"]},
  "湖的馈赠":     { name: "Boon of the Water", type: "Water"},
  "天真与渴盼":   { name: "Longing for Innocence", type: "Limited", rateUp6: ["Anjo Nala"]},
  "湖的涟漪":     { name: "Ripples on the Water", type: "Water"},
  "火花雀儿":     { name: "The Chirps of Flame", type: "Character", rateUp6: ["Spathodea"]},
  "第一滴雨":     { name: "The First Drop of Rain", type: "Regular"},
  "于湖中央":     { name: "Amongst the Lake", type: "Regular"}
};

const ACTIVE_BANNERS = [
  {
    key:      "誓言无有烬时",
    startUTC: "2026-07-14T10:00:00Z",
    endUTC:   "2026-07-28T09:59:00Z",
    image:    "static/banners/The_Oath_Unyielding.webp",
    rateUp:  ["Marsha", "Avgust", "Horropedia"]
  },
  {
    key:      "现实破译法",
    startUTC: "2026-07-02T10:00:00Z",
    endUTC:   "2026-07-23T09:59:00Z",
    image:    "static/banners/Deciphering_Reality.webp",
    rateUp:  ["Enigma", "Sweetheart", "Charlie"]
  },
  {
    key:      "湖的涟漪",
    startUTC: "2026-07-02T10:00:00Z",
    endUTC:   "2026-07-23T09:59:00Z",
    image:    "static/banners/Ripples_on_the_Water_3.6.webp",
    rateUp:  ["Recoleta", "Melania", "Tooth Fairy", "Willow", "Tuesday", "Isolde"]
  },
  {
    key:      "虹色五线谱",
    startUTC: "2026-06-30T10:00:00Z",
    endUTC:   "2026-07-14T09:59:00Z",
    image:    "static/banners/Playing_in_Rainbow_Clef.webp",
    rateUp:  ["Barcarola", "Bkornblume", "Charlie"]
  },
  {
    key:      "晴日决胜局",
    startUTC: "2026-06-16T10:00:00Z",
    endUTC:   "2026-06-30T09:59:00Z",
    image:    "static/banners/Clash_n_Slash.webp",
    rateUp:  ["J", "Sweetheart", "Click"]
  },
  {
    key:      "零重力漫游",
    startUTC: "2026-06-02T10:00:00Z",
    endUTC:   "2026-06-16T09:59:00Z",
    image:    "static/banners/Wirewalking_in_Zero_Gravity.webp",
    rateUp:  ["Kiperina", "Dikke", "Desert Flannel"]
  },
  {
    key:      "湖的涟漪",
    startUTC: "2026-05-28T10:00:00Z",
    endUTC:   "2026-07-02T09:59:00Z",
    image:    "static/banners/Ripples_on_the_Water_3.5.webp",
    rateUp:  ["Spathodea", "Tuesday", "Isolde", "Willow", "Sotheby", "Tooth Fairy"]
  },
  {
    key:      "湖的企盼",
    startUTC: "2026-06-01T05:00:00Z",
    endUTC:   "2026-06-15T04:59:00Z",
    image:    "static/banners/Yearning_of_the_Water_3.5.webp",
    rateUp:  ["Corvus", "Brume"]
  },
  {
    key:      "渡影归真",
    startUTC: "2026-06-18T10:00:00Z",
    endUTC:   "2026-07-02T09:59:00Z",
    image:    "static/banners/Conduit_of_the_Unseen.webp",
    rateUp: ["Ramona", "Loggerhead", "Kanjira"]
  },
  {
    key:      "奇异吸引子",
    startUTC: "2026-05-28T10:00:00Z",
    endUTC:   "2026-06-18T09:59:00Z",
    image:    "static/banners/The_Strange_Attractor.webp",
    rateUp: ["Lorentz Butterfly", "X", "Barbara"]
  },
  {
    key:     "虚影的实鉴",
    startUTC: "2026-05-19T10:00:00Z",
    endUTC:   "2026-06-02T09:59:00Z",
    image:    "static/banners/Observation_into_the_Mirrors.webp",
    rateUp: ["Kakania", "Mr. Duncan", "Yenisei"]
  },
];

const CHARACTERS = {
  3147: { name: "Ms. Stranger", rarity: 6},
  3146: { name: "Rhiannon", rarity: 6},
  3145: { name: "Everecho", rarity: 6},
  3144: { name: "Coppélia", rarity: 6},
  3143: { name: "Enigma", rarity: 6},
  3142: { name: "Ramona", rarity: 6},
  3141: { name: "Paper Heron", rarity: 6 },
  3139: { name: "Lorentz Butterfly", rarity: 6},
  3137: { name: "Cheng Heguang", rarity: 6},
  3135: { name: "Brume", rarity: 6 },
  3134: { name: "Beryl", rarity: 6 },
  3132: { name: "Corvus", rarity: 6 },
  3128: { name: "Charon", rarity: 6 },
  3127: { name: "Marsha", rarity: 6 },
  3126: { name: "Sentinel", rarity: 6 },
  3125: { name: "Rubuska", rarity: 6 },
  3124: { name: "Kassandra", rarity: 6 },
  3123: { name: "Ezio Auditore", rarity: 6 },
  3121: { name: "Moldir", rarity: 6 },
  3120: { name: "Nautika", rarity: 6 },
  3117: { name: "Kiperina", rarity: 6 },
  3116: { name: "Hissabeth", rarity: 6 },
  3114: { name: "Recoleta", rarity: 6 },
  3113: { name: "Aleph", rarity: 6 },
  3111: { name: "Noire", rarity: 6 },
  3110: { name: "Liang Yue", rarity: 6 },
  3109: { name: "Fatutu", rarity: 6 },
  3108: { name: "Barcarola", rarity: 6 },
  3107: { name: "Ulrich", rarity: 6 },
  3105: { name: "Flutterpage", rarity: 6 },
  3104: { name: "Willow", rarity: 6 },
  3102: { name: "Lopera", rarity: 6 },
  3100: { name: "Anjo Nala", rarity: 6 },
  3098: { name: "Tuesday", rarity: 6 },
  3097: { name: "Argus", rarity: 6 },
  3095: { name: "Mercuria", rarity: 6 },
  3094: { name: "J", rarity: 6 },
  3092: { name: "Igor", rarity: 6 },
  3088: { name: "Semmelweis", rarity: 6 },
  3087: { name: "Vila", rarity: 6 },
  3086: { name: "Lucy", rarity: 6 },
  3084: { name: "Getian", rarity: 6 },
  3083: { name: "Jiu Niangzi", rarity: 6 },
  3081: { name: "Isolde", rarity: 6 },
  3080: { name: "Kakania", rarity: 6 },
  3079: { name: "6", rarity: 6 },
  3077: { name: "Windsong", rarity: 6 },
  3074: { name: "Ezra", rarity: 6 },
  3073: { name: "Spathodea", rarity: 6 },
  3072: { name: "Shamane", rarity: 6 },
  3070: { name: "Kaalaa Baunaa", rarity: 6 },
  3066: { name: "37", rarity: 6 },
  3065: { name: "Marcus", rarity: 6 },
  3063: { name: "Pickles", rarity: 6 },
  3062: { name: "Melania", rarity: 6 },
  3056: { name: "Jessica", rarity: 6 },
  3053: { name: "Tooth Fairy", rarity: 6 },
  3052: { name: "Ms. NewBabel", rarity: 6 },
  3051: { name: "Eternity", rarity: 6 },
  3048: { name: "Voyager", rarity: 6 },
  3047: { name: "Medicine Pocket", rarity: 6 },
  3039: { name: "An-an Lee", rarity: 6 },
  3032: { name: "Centurion", rarity: 6 },
  3025: { name: "Regulus", rarity: 6 },
  3009: { name: "Sotheby", rarity: 6 },
  3007: { name: "A Knight", rarity: 6 },
  3004: { name: "Lilya", rarity: 6 },
  3003: { name: "Druvis III", rarity: 6 },
  
  3154: { name: "Silverwing Eagle", rarity: 5 },
  3122: { name: "Alexios", rarity: 5 },
  3118: { name: "Name Day", rarity: 5 },
  3115: { name: "Buddy Fairchild", rarity: 5 },
  3112: { name: "Loggerhead", rarity: 5 },
  3106: { name: "Brimley", rarity: 5 },
  3103: { name: "Mr. Duncan", rarity: 5 },
  3099: { name: "Barbara", rarity: 5 },
  3091: { name: "Lorelei", rarity: 5 },
  3082: { name: "Yenisei", rarity: 5 },
  3078: { name: "Avgust", rarity: 5 },
  3076: { name: "Ulu", rarity: 5 },
  3075: { name: "Desert Flannel", rarity: 5 },
  3071: { name: "Kanjira", rarity: 5 },
  3064: { name: "Diggers", rarity: 5 },
  3061: { name: "Horropedia", rarity: 5 },
  3060: { name: "Blonney", rarity: 5 },
  3049: { name: "Click", rarity: 5 },
  3043: { name: "Tennant", rarity: 5 },
  3041: { name: "Matilda", rarity: 5 },
  3038: { name: "Satsuki", rarity: 5 },
  3037: { name: "Necrologist", rarity: 5 },
  3024: { name: "Balloon Party", rarity: 5 },
  3023: { name: "Sonetto", rarity: 5 },
  3022: { name: "Dikke", rarity: 5 },
  3020: { name: "Bkornblume", rarity: 5 },
  3017: { name: "Charlie", rarity: 5 },
  3016: { name: "Baby Blue", rarity: 5 },
  3011: { name: "Sweetheart", rarity: 5 },
  3010: { name: "X", rarity: 5 },
  
  3138: { name: "Reed", rarity: 4},
  3136: { name: "Lady by the Lake", rarity: 4 },
  3101: { name: "White Rum", rarity: 4 },
  3058: { name: "Erick", rarity: 4 },
  3057: { name: "Mesmer Jr.", rarity: 4 },
  3046: { name: "Poltergeist", rarity: 4 },
  3044: { name: "Ms. Moissan", rarity: 4 },
  3042: { name: "Rabies", rarity: 4 },
  3033: { name: "TTT", rarity: 4 },
  3031: { name: "Cristallo", rarity: 4 },
  3028: { name: "APPLe", rarity: 4 },
  3026: { name: "Mondlicht", rarity: 4 },
  3018: { name: "Oliver Fog", rarity: 4 },
  3015: { name: "Pavia", rarity: 4 },
  3014: { name: "Bunny Bunny", rarity: 4 },
  3013: { name: "Зима", rarity: 4 },
  3006: { name: "Eagle", rarity: 4 },
  3005: { name: "Nick Bottom", rarity: 4 },
  
  3096: { name: "Pioneer", rarity: 3 },
  3055: { name: "Sputnik", rarity: 3 },
  3054: { name: "ONiON", rarity: 3 },
  3050: { name: "Darley Clatter", rarity: 3 },
  3045: { name: "Bette", rarity: 3 },
  3040: { name: "Twins Sleep", rarity: 3 },
  3036: { name: "John Titor", rarity: 3 },
  3035: { name: "Leilani", rarity: 3 },
  3034: { name: "aliEn T", rarity: 3 },
  3030: { name: "La Source", rarity: 3 },
  3012: { name: "The Fool", rarity: 3 },
  
  3059: { name: "Door", rarity: 2 },
  3027: { name: "Ms. Radio", rarity: 2 }
};

function getBannerName(cn) { return BANNERS[cn]?.name ?? cn; }
function getBannerType(cn) { return BANNERS[cn]?.type ?? "Character"; }

const PITY_SHARED_GROUP = { 3: "STANDARD", 12: "RIPPLES" };

function getPityKey(e) {
  return PITY_SHARED_GROUP[Number(e.poolType)] ?? e.poolId;
}

function getChar(id) {
  return CHARACTERS[id] || { name: `ID:${id}`, rarity: 5 };
}

const _charByName = Object.values(CHARACTERS).reduce((m, c) => (m[c.name] = c, m), {});
function getCharByName(name) { return _charByName[name] || null; }
