window.LOCALE = {
  guideBtn:           '📘 Guide',
  bannerHistoryBtn:   '📜 Banner History',
  dbManagement:       'Database Management',
  urlPlaceholder:     'https://game-re-en-service.sl916.com/query/summon?userId=xxx&token=xxx',
  importUrlBtn:       '🌐 Import by URL',
  selectFileBtn:      '📂 Select File',
  selectFileHint:     'Load individual pull history JSON file',
  exportDbBtn:        '💾 Download Database',
  importDbBtn:        '📂 Load Database',
  defaultProfile:     'Sonetto',
  profileSwitched:    'Profile switched',
  profileCreated:     (n) => `Profile "${n}" created`,
  profileDeleted:     'Profile deleted',
  profileCantDelete:  'Cannot delete the only profile',
  profileClearMain:   'Default profile cleared',
  promptProfileName:  'Enter profile name:',
  confirmClearMain:   'Clear default profile data?',
  confirmDelete:      'Delete profile and all its data?',
  bannerTimeline:     'Banners',
  activeBanners:      'Banners',
  activeBannersEmpty: 'No active banners at the moment.',
  viewTimeline:       'Timeline',
  viewGrid:           'Grid',
  tlLocalTime:        'Local time',
  countdownLabel:     'Banner ends in',
  countdownStartLabel:'Banner starts in',
  bannerEnded:        'Banner ended',
  bannerEndedShort:   'ended',
  startsInShort:      (time) => `starts in ${time}`,
  bannerCharacters:   'Banner characters',
  modalCountdownLabel:'Banner ends in',
  modalCountdownStartLabel:'Banner starts in',
  modalEnded:         'Ended',
  prydwenLabel:       'Open on Prydwen',
  statistics:         'Statistics',
  statTotalPulls:     'Total Pulls',
  statSixStars:       '6★ Obtained',
  statSixPct:         '6★ Rate',
  statAvgPity:        'Avg Pity',
  statFifty:          '50/50 Won',
  fifty_win:          'Won 50/50',
  fifty_lose:         'Lost 50/50',
  fifty_guaranteed:   'Guaranteed',
  chartsTitle:        'Charts',
  pityChart:          '6★ Pity Distribution',
  bannerStatPulls:    'Total pulls',
  bannerStatPity:     '6★ Pity',
  bannerPityHint:     'Pity at 70 pulls',
  recentSixStars:     'Recent 6★ Pulls',
  recentShowAll:      'Show all',
  recentCollapse:     'Collapse',
  sixStarsPlaceholder:'🌟 Your recent 6★ characters will appear here',
  monthlyChart:       'Monthly Pull Chart',
  chartPlaceholder1:  '📊 Pull statistics chart will appear here',
  chartPlaceholder2:  'after loading data',
  pullHistory:        'Pull History',
  filterRarity:       'Rarity:',
  filterAll:          'All',
  filterBannerType:   'Banner Type:',
  thBanner:           'Banner',
  thPity:             'Pity',
  thCharacter:        'Character',
  thDate:             'Date',
  thTotalPulls:       'Total Pulls',
  noData:             '📂 No data yet',
  storageQuota:       'Not enough browser storage space',
  enterUrl:           'Enter URL',
  invalidUrl:         'Invalid URL format',
  loading:            '⏳ Loading...',
  loadingData:        'Loading data...',
  serverError:        (s) => `Server returned error: ${s}`,
  importError:        (m) => `Import error: ${m}`,
  noNewPulls:         'All pulls already in database, no new entries added',
  addedPulls:         (a, t) => `Added ${a} new pulls (total ${t})`,
  dbEmpty:            'Database is empty',
  exportedProfiles:   (n) => `Exported ${n} profile(s)`,
  importDone:         'Import complete',
  fileNotJson:        'Please select a JSON file',
  fileReadError:      'File read error',
  invalidImportData:  'Invalid JSON structure. Expected Reverse 1999 pull history format',
  invalidPullFormat:  'Data does not match pull history format',
  dbCorruptProfiles:  'Database file corrupted: missing profiles field',
  dbCorruptPulls:     'Database file corrupted: missing pulls field',
  dbCorrupt:          'Database file corrupted',
  invalidDbFormat:    'Invalid database format',
  dbLoadedOldFormat:  'Database loaded (legacy format)',
  conflictTitle:        '⚠️ Profile Conflict',
  conflictSubtitle:     (n) => `Profile <b>${n}</b> already exists locally. Choose which one to keep:`,
  conflictLocal:        '💾 Local',
  conflictImported:     '📥 From File',
  conflictStatPulls:    'Pulls',
  conflictStatLast:     'Last pull',
  conflictStatSaved:    'File saved',
  conflictKeepLocal:    '💾 Keep Local',
  conflictUseImport:    '📥 Use from File',
  conflictCloudTitle:   '⚠️ Profile deleted in cloud',
  conflictCloudSub:     (n) => `Profile <b>${n}</b> exists locally but is missing from Google Drive. It may have been deleted on another device.`,
  conflictCloudLocal:   '💾 Local',
  conflictCloudDel:     '🗑️ Deleted in cloud',
  conflictKeepLocalBtn: '💾 Keep locally',
  conflictDeleteBtn:    '🗑️ Delete',
  scrollTop:          'Scroll to top',
  gdriveNotConnected:    'Not connected',
  gdriveExpired:         '⚠️ Session expired — click Connect to renew',
  gdriveConnect:         'Connect Google Drive',
  gdriveDisconnect:      'Disconnect',
  gdriveConnected:       'Connected',
  gdriveSyncing:         'Syncing',
  gdriveAuthError:       (e) => `Google auth error: ${e}`,
  gdriveConnectedMsg:    'Google Drive connected',
  gdriveSDKError:        'GIS SDK not loaded yet',
  gdriveDisconnectedMsg: 'Disconnected from Google Drive',
  gdriveSaveError:       (m) => `Drive save error: ${m}`,
  gdriveInvalidFile:     'Invalid Drive file format',
  gdriveLoadError:       (m) => `Drive load error: ${m}`,
  homeBtn:            '🏠 Home',
  methodsTitle:       'Import Methods',
  methodsIntro:       'There are three ways to get your pull history. Choose whichever works best for you.',
  method1Badge:       '⚡ Easiest',
  method1Title:       '🤖 Auto Link Grabber',
  method1Desc:        'The app automatically intercepts the link while you open your pull history in-game. The link is copied to your clipboard and can be pasted into the tracker with one click.',
  method2Badge:       '⚡ Easy',
  method2Title:       '🌐 Import by URL',
  method2Desc:        'Get the URL via Fiddler or the auto-grabber and paste it directly into the tracker — no file download needed, data loads automatically.',
  method3Badge:       '🔧 Manual',
  method3Title:       '📂 File Upload',
  method3Desc:        'Save the pull history JSON file via Fiddler or browser and upload it directly to the tracker.',
  g1Title:      'Method 1 — Auto Link Grabber',
  g1Recommended:'Recommended',
  g1Desc:       'A small utility that automatically intercepts your pull history link while you open it in-game. No Fiddler setup required.',
  g1Download:   'Download .exe',
  g1Tip:        'The utility temporarily enables a local proxy, intercepts the pull history request, and automatically copies the link to your clipboard. No game data is modified.',
  g1Step1:      'Download the latest release from the Releases page and run <b>R1999LinkGrabber.exe</b>',
  g1Step2:      'The console will show:',
  g1Step3:      'Launch <b>Reverse: 1999</b> and open the pull history page <b>(Summon → Record)</b>',
  g1Step4:      'The app will automatically find and copy the link:',
  g1Step5:      'Paste the link into the <b>🌐 Import by URL</b> field on the tracker\'s main page',
  g1Warn:       '<b>Important:</b> do not close the console window with the X button — this may leave the system proxy enabled. Exit only via <b>Ctrl + C</b> or let the program finish automatically after capturing the link.',
  g1ProxyNote:  'If the proxy remains enabled: <b>Settings → Network & Internet → Proxy → Manual proxy setup</b> → disable <b>"Use a proxy server"</b>.',
  g1PythonNote: 'To run the Python script directly — requires Python 3.10–3.12 and dependencies:',
  g2Title:   'Method 2 — Import by URL via Fiddler',
  g2Desc:    'If you prefer not to use the auto-grabber, you can get the URL manually via <b>Fiddler Classic</b>.',
  g2Download:'Download Fiddler',
  g2Step1:   'Launch <b>Fiddler</b> and <b>Reverse: 1999</b>',
  g2Step2:   'Open pull history in-game <b>(Summon → Record)</b>',
  g2Step3:   'In Fiddler find a request like:',
  g2Step4:   'Select the row → <b>Right-click → Copy → Just URL</b>',
  g2Step5:   'Paste the link into the <b>🌐 Import by URL</b> field on the tracker\'s main page and click the button',
  g2Tip:     'Data loads automatically via proxy — no file download needed.',
  g3Title:  'Method 3 — Manual JSON File Upload',
  g3Step1:  'Get the URL using any method above',
  g3Step2:  'Open the URL in your browser',
  g3Step3:  'Save the page as a file: <b>Right-click → Save As</b>',
  g3Step4:  'On the main page click <b>📂 Select File</b> and choose the saved JSON',
  g3Warn:   '<b>Note:</b> the «📂 Select File» button only accepts the original in-game file. To load a previously saved tracker database, use the <b>«📂 Load Database»</b> button instead.',
  profilesTitle: 'Managing Profiles',
  profileLi1:    'Create a new profile — click <b>➕</b>',
  profileLi2:    'Switch profiles — use the dropdown',
  profileLi3:    'Delete a profile — click <b>➖</b> (the default profile cannot be deleted, only cleared)',
  profileTip:    'Profiles are stored locally in the browser. To transfer to another device, use <b>💾 Download Database</b> or connect <b>Google Drive</b> — all profiles will sync automatically.',
  dbTitle:   'Export & Import Database',
  dbLi1:     '<b>💾 Download Database</b> — saves <b>all profiles</b> into a single JSON file for backup or transfer to another device',
  dbLi2:     '<b>📂 Load Database</b> — loads a previously saved database file',
  dbTip:     'When loading a file, the tracker compares each profile with local data. If a profile from the file matches — it is ignored. If the file has <b>more</b> pulls — the profile is updated automatically. If the file has <b>fewer</b> pulls — a dialog appears to choose whether to keep local data or replace it.',
  dbWarn:    '<b>Note:</b> the «📂 Load Database» button is only for files previously saved via «💾 Download Database». To load the original in-game file, use the <b>«📂 Select File»</b> button.',
  gdriveGuideTitle: 'Google Drive Sync',
  gdriveGuideDesc:  'The tracker supports automatic sync of all profiles via Google Drive. Data is stored in a hidden app folder — it does not appear in your Drive.',
  gdriveStep1:      'Click <b>Connect Google Drive</b> in the database management section',
  gdriveStep2:      'Sign in to your Google account and grant access',
  gdriveStep3:      'The tracker will automatically load data from the cloud and save changes going forward',
  gdriveTip1:       'After connecting, the status changes to <b>Connected</b>. After each pull import, data is automatically saved to the cloud 2 seconds after the last change.',
  gdriveTip2:       'The connection persists between sessions. On the next visit, the tracker will automatically reconnect and sync without requiring a new sign-in.',
  gdriveWarn:       '<b>Conflicts:</b> if the cloud has more data — it is applied automatically. If less — a dialog appears for you to choose.',
  dateLocale:  'en-US',
  timerDays:   'd',
  timerHours:  'h',
  timerMin:    'm',
  days:        ['Sun','Mon','Tue','Wed','Thu','Fri','Sat'],
  months:      ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'],
  monthsFull:  ['January','February','March','April','May','June','July','August','September','October','November','December'],

};
